version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  db-data: